import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    BASEHUB_TOKEN: z.string().min(1).startsWith('bshb_pk_').optional(),
    RESEND_AUDIENCE_ID: z.string().min(1).optional(),
    RESEND_TOKEN: z.string().min(1).startsWith('re_').optional(),
    BETTERSTACK_API_KEY: z.string().min(1).optional(),
    BETTERSTACK_URL: z.string().min(1).optional(),
    GITHUB_TOKEN: z.string().min(1).startsWith('github_pat_').optional(),
    KV_REST_API_URL: z.string().min(1).url().optional(),
    KV_REST_API_TOKEN: z.string().min(1).optional(),
    RESEND_FROM: z.string().min(1).email().optional(),
    RESEND_TO: z.string().min(1).email().optional(),
    SMTP_HOST: z.string().min(1).optional(),
    SMTP_PORT: z.string().min(1).optional(),
    SMTP_USER: z.string().min(1).optional(),
    SMTP_PASS: z.string().min(1).optional(),
    VERCEL_TOKEN: z.string().min(1).optional(),
    EDGE_CONFIG: z.string().min(1).url().optional(),
    EDGE_CONFIG_ID: z.string().min(1).startsWith('ecfg_').optional(),
    SPOTIFY_CLIENT_ID: z.string().min(1).optional(),
    SPOTIFY_CLIENT_SECRET: z.string().min(1).optional(),
    SPOTIFY_REFRESH_TOKEN: z.string().min(1).optional(),
    STEAM_ID: z.string().min(1).optional(),
    STEAM_API_KEY: z.string().min(1).optional(),
    YOUTUBE_API_KEY: z.string().min(1).optional(),

    // Added by Vercel
    VERCEL_PROJECT_PRODUCTION_URL: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_LOGO_DEV_TOKEN: z.string().min(1).startsWith('pk_').optional(),
  },
  runtimeEnv: {
    BASEHUB_TOKEN: process.env.BASEHUB_TOKEN,
    RESEND_AUDIENCE_ID: process.env.RESEND_AUDIENCE_ID,
    RESEND_TOKEN: process.env.RESEND_TOKEN,
    BETTERSTACK_API_KEY: process.env.BETTERSTACK_API_KEY,
    BETTERSTACK_URL: process.env.BETTERSTACK_URL,
    GITHUB_TOKEN: process.env.GITHUB_TOKEN,
    KV_REST_API_URL: process.env.KV_REST_API_URL,
    KV_REST_API_TOKEN: process.env.KV_REST_API_TOKEN,
    RESEND_FROM: process.env.RESEND_FROM,
    RESEND_TO: process.env.RESEND_TO,
    SMTP_HOST: process.env.SMTP_HOST,
    SMTP_PORT: process.env.SMTP_PORT,
    SMTP_USER: process.env.SMTP_USER,
    SMTP_PASS: process.env.SMTP_PASS,
    VERCEL_TOKEN: process.env.VERCEL_TOKEN,
    EDGE_CONFIG: process.env.EDGE_CONFIG,
    EDGE_CONFIG_ID: process.env.EDGE_CONFIG_ID,
    SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID,
    SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET,
    SPOTIFY_REFRESH_TOKEN: process.env.SPOTIFY_REFRESH_TOKEN,
    STEAM_ID: process.env.STEAM_ID,
    STEAM_API_KEY: process.env.STEAM_API_KEY,
    YOUTUBE_API_KEY: process.env.YOUTUBE_API_KEY,
    NEXT_PUBLIC_LOGO_DEV_TOKEN: process.env.NEXT_PUBLIC_LOGO_DEV_TOKEN,
    VERCEL_PROJECT_PRODUCTION_URL: process.env.VERCEL_PROJECT_PRODUCTION_URL,
  },
});
